adv_modules:
  xc: false
aws:
  auth_profile: terraform
  aws_access_key_id: <AWS ACCESS KEY>
  aws_secret_access_key: <AWS SECRET KEY>
  aws_session_token: <AWS SESSION TOKEN>
  region_site_1: eu-central-1
  region_site_2: eu-west-1
  tmp_aws_cred: true
student:
  email: <STUDENT E-MAIL>
  ip-address: <DO NOT CHANGE>
  name: <STUDENT NAME>
f5:
  f5_password: DefaultLabPwd!2026
xC:
  p12_auth: ../setup-init/.xC/f5-emea-ent.console.ves.volterra.io.api-creds.p12
  p_12_pwd: <P12 PASSWORD STRING>
  tenant: <XC TENANT NAME>
  tenant_shrt: <XC TENANT SHORT NAME>
  tenant_api: https://<TENANT>.console.ves.volterra.io/api
  namespace: <NAMESPACE>